spring:
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      time-to-live: 60000
      cache-null-values: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/userservice?useSSL=false&serverTimezone=Europe/Athens
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-version: 1.00
    baseline-on-migrate: true
    validate-on-migrate: true

  redis:
    short-cache-in-seconds: 50
    long-cache-in-hours: 10
